//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set this property because it is not null. Use IBinarySearchTree.Insert instead.
        /// </summary>
        internal static string BinarySearchNodePropertyNotNull {
            get {
                return ResourceManager.GetString("BinarySearchNodePropertyNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node that was passed in cannot be rebalanced in this direction.
        /// </summary>
        internal static string CannotRebalanceInThisDirection {
            get {
                return ResourceManager.GetString("CannotRebalanceInThisDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children already initialized.
        /// </summary>
        internal static string ChildrenAlreadyInitialized {
            get {
                return ResourceManager.GetString("ChildrenAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node passed in to DeleteNode was not a child of the parent node as expected.
        /// </summary>
        internal static string DeleteNodeNotChildOf {
            get {
                return ResourceManager.GetString("DeleteNodeNotChildOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the node from the tree because the tree does not contain the node.
        /// </summary>
        internal static string DeleteNodeNotFound {
            get {
                return ResourceManager.GetString("DeleteNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent node must differ from the child node.
        /// </summary>
        internal static string DeleteNodeParentMatchesChild {
            get {
                return ResourceManager.GetString("DeleteNodeParentMatchesChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node has two non-null children, expected one or less.
        /// </summary>
        internal static string DeleteWithTwoChildrenNotAllowed {
            get {
                return ResourceManager.GetString("DeleteWithTwoChildrenNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find depth of node in tree because the tree does not contain the node.
        /// </summary>
        internal static string DepthNodeNotFound {
            get {
                return ResourceManager.GetString("DepthNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert a node if the node&apos;s value is already contained in the tree.
        /// </summary>
        internal static string InsertDuplicate {
            get {
                return ResourceManager.GetString("InsertDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left child must be smaller than current node&apos;s value. Use IBinarySearchTree.insert instead.
        /// </summary>
        internal static string LeftChildMustBeSmaller {
            get {
                return ResourceManager.GetString("LeftChildMustBeSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap node not found.
        /// </summary>
        internal static string NoSwapNode {
            get {
                return ResourceManager.GetString("NoSwapNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node was not found within the tree.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null parent was expected.
        /// </summary>
        internal static string NullParentExpected {
            get {
                return ResourceManager.GetString("NullParentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right child must be bigger than the current node&apos;s value. Use IBinarySearchTree.insert instead.
        /// </summary>
        internal static string RightChildMustBeBigger {
            get {
                return ResourceManager.GetString("RightChildMustBeBigger", resourceCulture);
            }
        }
    }
}
